version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  service-registry:
    build:
      context: .
      dockerfile: service-registry/Dockerfile
    container_name: service-registry
    ports:
      - "8761:8761"

  person-service:
    build: ./person-service
    container_name: person-service
    depends_on:
      - service-registry
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka

  medical-service:
    build: ./medical-service
    container_name: medical-service
    depends_on:
      - kafka
      - service-registry
      - person-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      PERSON_SERVICE_URL: http://person-service:8081

  qr-service:
    build: ./qr-service
    container_name: qr-service
    depends_on:
      - kafka
      - service-registry
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - service-registry
      - person-service
      - medical-service
      - qr-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
      MEDICAL_SERVICE_URL: http://medical-service:8080
      PERSON_SERVICE_URL: http://person-service:8081
      QR_SERVICE_URL: http://qr-service:8082
